version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: git submodule update --init --recursive & cmake -G "Visual Studio 15 2017 Win64" .
build:
  project: SNAKE.vcxproj
  verbosity: minimal
after_build:
- cmd: 7z a honours.zip %APPVEYOR_BUILD_FOLDER%/bin/%CONFIGURATION%/SNAKE.exe %APPVEYOR_BUILD_FOLDER%/bin/%CONFIGURATION%/*.dll %APPVEYOR_BUILD_FOLDER%/bin/%CONFIGURATION%/res
artifacts:
- path: /*.zip
  name: honours_zip
- path: installer/*.exe
  name: honours_installer
deploy:
- provider: GitHub
  auth_token:
    secure: wKyML1y5xwS4ef0KqcWR2L7yK2SALPfyfXBgzUEBAd6bj47LowG9mSdlGHhwx7K8
  artifact: honours_zip, honours_installer
  prerelease: true